# write docker compose to setup a mysql database

services:
  soc_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - ./mysql:/var/lib/mysql

