name: Deploy on server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
    - name: Execute commands over ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /path/to/your/project
          git pull
          cd client/chakra-client
          npm install
          npm run build
          cd ../backend
          npm install
          npm start
          sudo systemctl restart nginx